<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>${diffdrive_update_rate}</updateRate>
            <leftJoint>right_wheel_joint</leftJoint>
            <rightJoint>left_wheel_joint</rightJoint>
            <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
            <wheelTorque>${wheel_torque}</wheelTorque>
            <!--wheelAcceleration>${wheel_accel}</wheelAcceleration-->
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>
</robot>